# Generated by Django 6.0.4 on 2026-05-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NaturezaDespesa',
            fields=[
                ('ano', models.CharField(primary_key=True, serialize=False)),
                ('grupo_cod', models.CharField()),
                ('grupo_desc', models.CharField()),
                ('categoria_cod', models.CharField()),
                ('categoria_desc', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('acao_cod', models.CharField()),
                ('acao_desc', models.CharField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ano', 'acao_cod'), name='unique_ano_acao_cod')],
            },
        ),
        migrations.CreateModel(
            name='ElementoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField()),
                ('elemento_item_cod', models.CharField()),
                ('elemento_item_desc', models.CharField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ano', 'elemento_item_cod'), name='unique_ano_elemento_item_cod')],
            },
        ),
        migrations.CreateModel(
            name='FonteRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField()),
                ('fonte_cod', models.CharField()),
                ('fonte_desc', models.CharField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ano', 'fonte_cod'), name='unique_ano_fonte_cod')],
            },
        ),
        migrations.CreateModel(
            name='FuncionalProgramatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField()),
                ('uo_cod', models.CharField()),
                ('funcao_cod', models.CharField()),
                ('funcao_desc', models.CharField()),
                ('subfuncao_cod', models.CharField()),
                ('subfuncao_desc', models.CharField()),
                ('programa_cod', models.CharField()),
                ('programa_desc', models.CharField()),
                ('acao_cod', models.CharField()),
                ('acao_desc', models.CharField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ano', 'uo_cod', 'acao_cod'), name='unique_ano_uo_acao_cod')],
            },
        ),
        migrations.CreateModel(
            name='NaturezaReceita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField()),
                ('rec_cod', models.CharField()),
                ('rec_desc', models.CharField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ano', 'rec_cod'), name='unique_ano_rec_cod')],
            },
        ),
        migrations.CreateModel(
            name='UnidadeOrcamentaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField()),
                ('orgao_vinculacao_cod', models.CharField()),
                ('orgao_vinculacao_nome', models.CharField()),
                ('poder_cod', models.CharField()),
                ('poder_desc', models.CharField()),
                ('uo_cod', models.CharField()),
                ('uo_nome', models.CharField()),
                ('uo_sigla', models.CharField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ano', 'uo_cod'), name='unique_ano_uo_cod')],
            },
        ),
    ]
