# Generated by Django 6.0.4 on 2026-05-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('pk', models.CompositePrimaryKey('ano', 'acao_cod', blank=True, editable=False, primary_key=True, serialize=False)),
                ('chave_acao', models.CharField()),
                ('ano', models.IntegerField()),
                ('acao_cod', models.IntegerField()),
                ('acao_desc', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='ElementoItem',
            fields=[
                ('pk', models.CompositePrimaryKey('ano', 'elemento_item_cod', blank=True, editable=False, primary_key=True, serialize=False)),
                ('chave_elemento_item', models.CharField()),
                ('ano', models.IntegerField()),
                ('elemento_item_cod', models.IntegerField()),
                ('elemento_item_desc', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='FonteRecurso',
            fields=[
                ('pk', models.CompositePrimaryKey('ano', 'fonte_cod', blank=True, editable=False, primary_key=True, serialize=False)),
                ('chave_fonte_recurso', models.CharField()),
                ('ano', models.IntegerField()),
                ('fonte_cod', models.IntegerField()),
                ('fonte_desc', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FuncionalProgramatica',
            fields=[
                ('pk', models.CompositePrimaryKey('ano', 'uo_cod', 'acao_cod', blank=True, editable=False, primary_key=True, serialize=False)),
                ('chave_funcional_programatica', models.CharField()),
                ('ano', models.IntegerField()),
                ('uo_cod', models.IntegerField()),
                ('funcao_cod', models.IntegerField()),
                ('funcao_desc', models.CharField()),
                ('subfuncao_cod', models.IntegerField()),
                ('subfuncao_desc', models.CharField()),
                ('programa_cod', models.IntegerField()),
                ('programa_desc', models.CharField()),
                ('acao_cod', models.IntegerField()),
                ('acao_desc', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='NaturezaDespesa',
            fields=[
                ('ano', models.IntegerField(primary_key=True, serialize=False)),
                ('grupo_cod', models.IntegerField()),
                ('grupo_desc', models.CharField()),
                ('categoria_cod', models.IntegerField()),
                ('categoria_desc', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='NaturezaReceita',
            fields=[
                ('pk', models.CompositePrimaryKey('ano', 'rec_cod', blank=True, editable=False, primary_key=True, serialize=False)),
                ('chave_natureza_receita', models.CharField()),
                ('ano', models.IntegerField()),
                ('rec_cod', models.IntegerField()),
                ('rec_desc', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='UnidadeOrcamentaria',
            fields=[
                ('pk', models.CompositePrimaryKey('ano', 'uo_cod', blank=True, editable=False, primary_key=True, serialize=False)),
                ('chave_uo', models.CharField()),
                ('ano', models.IntegerField()),
                ('orgao_vinculacao_cod', models.IntegerField()),
                ('orgao_vinculacao_nome', models.CharField()),
                ('poder_cod', models.IntegerField()),
                ('poder_desc', models.CharField()),
                ('uo_cod', models.IntegerField()),
                ('uo_nome', models.CharField()),
                ('uo_sigla', models.CharField()),
                ('uo_sigla_current', models.CharField()),
            ],
        ),
    ]
