from django.db import models


class AlteracaoOrcamentaria(models.Model):
    ano = models.IntegerField()
    mes_cod = models.IntegerField()
    data_publicacao = models.DateTimeField(input_formats="%Y-%m-%d %H:%M:%S")
    data_registro = models.DateTimeField(input_formats="%Y-%m-%d %H:%M:%S")
    decreto_num = models.IntegerField()
    lei_aprovacao = models.IntegerField()
    poder_cod = models.IntegerField()
    uo_cod = models.IntegerField()
    funcao_cod = models.IntegerField()
    programa_cod = models.IntegerField()
    acao_cod = models.IntegerField()
    grupo_cod = models.IntegerField()
    modalidade_cod = models.IntegerField()
    iag_cod = models.IntegerField()
    fonte_cod = models.IntegerField()
    ipu_cod = models.IntegerField()
    origem_credito_cod = models.IntegerField()
    origem_credito_desc = models.CharField()
    vlr_suplementacao = FloatField()
    vlr_anulacao = FloatField()
    vlr_credito_inicial = FloatField()
    vlr_credito_autorizado = FloatField()
