from django.db import models


class Execucao(models.Model):
    ano = models.CharField()
    mes_cod = models.CharField()
    uo_cod = models.CharField()
    ue_cod = models.CharField()
    upg_cod = models.CharField()
    uo_fin_cod = models.CharField()
    funcao_cod = models.CharField()
    subfuncao_cod = models.CharField()
    programa_cod = models.CharField()
    acao_cod = models.CharField()
    grupo_cod = models.CharField()
    modalidade_cod = models.CharField()
    iag_cod = models.CharField()
    fonte_cod = models.CharField()
    ipu_cod = models.CharField()
    elemento_item_cod = models.CharField()
    elemento_dea_cod = models.CharField()
    item_dea_cod = models.CharField()
    num_processo_compra = models.CharField()
    licitacao_modalidade = models.CharField()
    cnpj_cpf_formatado = models.CharField()
    num_contrato_saida = models.CharField()
    num_contrato_entrada = models.CharField()
    num_obra = models.CharField()
    num_empenho = models.CharField()
    vlr_empenhado = models.FloatField()
    vlr_liquidado = models.FloatField()
    vlr_liquidado_retido = models.FloatField()
    vlr_pago_orcamentario = models.FloatField()
    vlr_pago_financeiro = models.FloatField()
